services:
  - type: web
    name: splash-electronics-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production
